select '2018.01' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.02.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.02' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.03.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.03' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.04.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.04' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.05.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.05' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.06.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.06' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.07.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.07' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.08.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.08' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.09.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.09' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.10.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.10' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.11.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.11' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2018.12.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
union all
select '2018.12' as Year,
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2007) as 'KN2007',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2008) as 'KN2008',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2009) as 'KN2009',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2010) as 'KN2010',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2011) as 'KN2011',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2012) as 'KN2012',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2013) as 'KN2013',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2014) as 'KN2014',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2015) as 'KN2015',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2016) as 'KN2016',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2017) as 'KN2017',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2018) as 'KN2018',
(select count(*) from AppleMusic join Song on AppleMusic.KNID = Song.KNID where AppleMusic.DateAdded < '2019.01.01' and AppleMusic.InLibrary = 1 and Song.KNYEAR = 2019) as 'KN2019'
