SELECT s.KNYEAR, 'January' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID 
WHERE t.Date BETWEEN 20230104 AND 20230131 --START DATE NEED TO CHANGE
AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'February' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20230201 AND 20230231 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'March' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20230301 AND 20230331 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'April' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20230401 AND 20230431 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'May' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20230501 AND 20230531 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'June' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20230601 AND 20230631 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'July' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20230701 AND 20230731 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'August' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20230801 AND 20230831 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'September' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20230901 AND 20230931 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'October' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20231001 AND 20231031 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'November' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID WHERE t.Date BETWEEN 20231101 AND 20231131 AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID UNION ALL
SELECT s.KNYEAR, 'December' as Month, '' as SortOrder, t.SongTitle AS 'Song Title', t.ArtistTitle AS 'Artist Title', COUNT(*) AS 'Rank' FROM SOTD t JOIN Song s ON s.ID = t.SongID 
WHERE t.Date BETWEEN 20231201 AND 20231227 --END DATE NEED TO CHANGE
AND t.IsShortPreview = 0 GROUP BY t.SongTitle, t.ArtistTitle, t.SongID
ORDER BY Month, COUNT(*) DESC -- OVERALL SORT DUE TO UNION ALL